### ISSUE TITLE
Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Lesmiscore/rcon-client#3]
```
MAC OSX Lion 10.7.3

java -jar RConClient.jar 
Exception in thread "main" java.lang.UnsupportedClassVersionError: 
org/minecraft/rconclient/RConClient : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)

java -version
java version "1.6.0_31"
Java(TM) SE Runtime Environment (build 1.6.0_31-b04-415-11M3635)
Java HotSpot(TM) 64-Bit Server VM (build 20.6-b01-415, mixed mode)
```

Original issue reported on code.google.com by `aphe...@gmail.com` on 5 Jun 2012 at 11:52

**Comment by GoogleCodeExporter** [comment]
```
Hallo,

RConClient is currently coded and compiled with Java SE 7. This is why the 
class files have a version 51 and for that can only be run using the Java SE 7 
JVM.

I will make a note of it on this project page. I will also leave this issue 
open till I have fixed this compatibility issue.

Regards,
Vincent
```

Original comment by `Vincent....@gmail.com` on 6 Jun 2012 at 5:29
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
There is a note on the project page about the requirement for JavaSE 7.

I will not backport the code to JavaSE 6.
```

Original comment by `Vincent....@gmail.com` on 21 Nov 2012 at 9:55
- Changed state: **WontFix**
